import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarGuard from "@/components/NavbarGuard";
import Footer from "@/components/Footer";
import AppProviders from "@/components/AppProviders";
import { getSettings } from "@/lib/function";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarGuard settings={settings} />
        <AppProviders>
          <main className="app-gradient-bg">{children}</main>
        </AppProviders>
        <Footer settings={settings} />
      </body>
    </html>
  );
}
